# Generated by Django 4.2.8 on 2023-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_courses_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="slug",
            field=models.SlugField(default=1, max_length=255, verbose_name="Авто URL"),
            preserve_default=False,
        ),
    ]
