# Generated by Django 4.2.8 on 2023-12-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_courses_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="Авто URL"
            ),
        ),
    ]
