# Generated by Django 4.2.8 on 2023-12-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_usercourse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "verbose_name": "Группа курса",
                "verbose_name_plural": "Группы курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="usercourse",
            options={
                "verbose_name": "Разрешение для пользователя на курс",
                "verbose_name_plural": "Разрешения для пользователей на курсы",
            },
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.courses"
            ),
        ),
    ]
