# Generated by Django 4.2.8 on 2024-01-04 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0006_alter_course_options_alter_usercourse_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercourse",
            name="access_granted",
            field=models.BooleanField(default=False, verbose_name="Разрешено"),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courses",
                verbose_name="Курсы",
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
