# Generated by Django 4.2.8 on 2024-01-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_usercourse_access_granted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="course_description_en",
            field=models.TextField(null=True, verbose_name="Описание курса"),
        ),
        migrations.AddField(
            model_name="courses",
            name="course_description_ru",
            field=models.TextField(null=True, verbose_name="Описание курса"),
        ),
        migrations.AddField(
            model_name="courses",
            name="course_name_en",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Название курса"
            ),
        ),
        migrations.AddField(
            model_name="courses",
            name="course_name_ru",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Название курса"
            ),
        ),
    ]
