# Generated by Django 4.2.8 on 2024-01-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_courses_course_description_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="course_name_en",
        ),
        migrations.RemoveField(
            model_name="courses",
            name="course_name_ru",
        ),
    ]
