# Generated by Django 5.0.1 on 2024-02-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_courses_course_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': 'Разрешение на курс', 'verbose_name_plural': 'Разрешения на курсы'},
        ),
        migrations.AddField(
            model_name='usercourse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
