# Generated by Django 5.0.1 on 2024-02-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_usercourse_options_usercourse_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
