# Generated by Django 5.0.1 on 2024-02-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_courses_course_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
