# Generated by Django 5.0.1 on 2024-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_usercourse_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания курса'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
