# Generated by Django 5.0.1 on 2024-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_usercourse_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания курса'),
        ),
    ]
