# Generated by Django 5.0.1 on 2024-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_usercourse_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания курса'),
        ),
    ]
