# Generated by Django 4.2.8 on 2023-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bg_image",
                    models.ImageField(
                        upload_to="slider/", verbose_name="Фоновое Изображение слайдера"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="slider/", verbose_name="Изображение слайдера"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Загаловок слайдера"),
                ),
                (
                    "suptitle",
                    models.CharField(
                        blank=True,
                        help_text="Уроки на кыргызском языке",
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок слайдера 1",
                    ),
                ),
                (
                    "suptitle2",
                    models.CharField(
                        blank=True,
                        help_text="Возможность подготовиться в любое время",
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок слайдера 2",
                    ),
                ),
                (
                    "suptitle3",
                    models.CharField(
                        blank=True,
                        help_text="99% наших выпусников являются стипендиатами",
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок слайдера 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайдер",
                "verbose_name_plural": "Слайдеры",
            },
        ),
    ]
