# Generated by Django 4.2.8 on 2023-12-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="paket/", verbose_name="Фото тарифа"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название тарифа"),
                ),
                (
                    "ent",
                    models.IntegerField(
                        help_text="В цифрах: 12",
                        verbose_name="Количество возможностей для сдачи ЕНТ:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
            },
        ),
    ]
