# Generated by Django 4.2.8 on 2023-12-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_subject_date_created_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
