# Generated by Django 4.2.8 on 2023-12-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0012_lesson_delete_subject_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
    ]
