# Generated by Django 4.2.8 on 2023-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0014_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birthday",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Дата рождения"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default=1, max_length=255, verbose_name="Город"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="clas",
            field=models.CharField(
                choices=[
                    ("1_class", "1 класс"),
                    ("2_class", "2 класс"),
                    ("3_class", "3 класс"),
                    ("4_class", "4 класс"),
                    ("5_class", "5 класс"),
                    ("6_class", "6 класс"),
                    ("7_class", "7 класс"),
                    ("8_class", "8 класс"),
                    ("9_class", "9 класс"),
                    ("10_class", "10 класс"),
                    ("11_class", "11 класс"),
                ],
                default=1,
                max_length=255,
                verbose_name="Класс",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="place_learn",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Место учебы"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="region",
            field=models.CharField(default=1, max_length=255, verbose_name="Область"),
            preserve_default=False,
        ),
    ]
