# Generated by Django 4.2.8 on 2023-12-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0015_userprofile_birthday_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birthday",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="clas",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1_class", "1 класс"),
                    ("2_class", "2 класс"),
                    ("3_class", "3 класс"),
                    ("4_class", "4 класс"),
                    ("5_class", "5 класс"),
                    ("6_class", "6 класс"),
                    ("7_class", "7 класс"),
                    ("8_class", "8 класс"),
                    ("9_class", "9 класс"),
                    ("10_class", "10 класс"),
                    ("11_class", "11 класс"),
                ],
                max_length=255,
                null=True,
                verbose_name="Класс",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="place_learn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место учебы"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="region",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Область"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
