# Generated by Django 4.2.8 on 2023-12-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0016_alter_userprofile_birthday_alter_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
