# Generated by Django 4.2.8 on 2023-12-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0018_alter_userprofile_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="instagram",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ссылка на Instagram",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="tiktok",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Ссылка на Tiktok"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="youtube",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Ссылка на Youtube"
            ),
        ),
    ]
