# Generated by Django 4.2.8 on 2023-12-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0019_settings_instagram_settings_tiktok_settings_youtube"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
