# Generated by Django 4.2.8 on 2024-01-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0020_alter_userprofile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="clas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Класс"
            ),
        ),
    ]
