# Generated by Django 4.2.8 on 2024-01-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "settings",
            "0022_paket_price_paket_slug_paket_title_en_paket_title_ru_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="title_ru",
        ),
    ]
