# Generated by Django 4.2.8 on 2024-01-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0023_remove_settings_title_en_remove_settings_title_ru"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachers",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="name_ru",
        ),
    ]
