# Generated by Django 5.0.1 on 2024-02-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0033_remove_question_options_question_option1_and_more'),
        ('settings', '0027_remove_paket_available_modules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='selected_paket',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='moduls',
            field=models.ManyToManyField(blank=True, null=True, to='lessons.moduls', verbose_name='Доступные Модули'),
        ),
    ]
