# Generated by Django 5.0.1 on 2024-01-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_moduls_lesson_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduls',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.moduls', verbose_name='Модуль'),
            preserve_default=False,
        ),
    ]
