# Generated by Django 5.0.1 on 2024-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_moduls_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/', verbose_name='Файл для презентации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/', verbose_name='Файл для конспекта'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.TextField(help_text="Вставьте ссылку из ютуба код Embed\n    <br>Например:\n    <br>Перейдите на страницу видео на YouTube.\n    <br>Нажмите на кнопку 'Поделиться' под видео.\n    <br>Выберите 'Встроить'\n    <br>Скопируйте предоставленный код и вставьте его в ваш HTML-код.", verbose_name='Ссылка на видео'),
        ),
    ]
