# Generated by Django 5.0.1 on 2024-01-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
