# Generated by Django 5.0.1 on 2024-01-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.TextField(blank=True, help_text="Вставьте ссылку из ютуба код Embed\n    <br>Например:\n    <br>Перейдите на страницу видео на YouTube.\n    <br>Нажмите на кнопку 'Поделиться' под видео.\n    <br>Выберите 'Встроить'\n    <br>Скопируйте предоставленный код и вставьте его в ваш HTML-код.", null=True, verbose_name='Ссылка на видео'),
        ),
    ]
