# Generated by Django 5.0.1 on 2024-01-25 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='TestLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос теста')),
                ('choice_1', models.CharField(max_length=255, verbose_name='Вариант ответа 1')),
                ('choice_2', models.CharField(max_length=255, verbose_name='Вариант ответа 2')),
                ('choice_3', models.CharField(max_length=255, verbose_name='Вариант ответа 3')),
                ('choice_4', models.CharField(max_length=255, verbose_name='Вариант ответа 4')),
                ('correct_answer', models.PositiveIntegerField(choices=[(1, 'Вариант ответа 1'), (2, 'Вариант ответа 2'), (3, 'Вариант ответа 3'), (4, 'Вариант ответа 4')], verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Пояснение к правильному ответу')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lessons.moduls', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Тестовый вопрос',
                'verbose_name_plural': 'Тестовые вопросы',
            },
        ),
    ]
