# Generated by Django 5.0.1 on 2024-01-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_alter_lesson_video_testlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('content', models.TextField(verbose_name='Текст теста')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lessons.moduls', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Тестовый вопрос',
                'verbose_name_plural': 'Тестовые вопросы',
            },
        ),
        migrations.DeleteModel(
            name='TestLesson',
        ),
    ]
