# Generated by Django 5.0.1 on 2024-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_test_delete_testlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('option1', models.CharField(max_length=255, verbose_name='Вариант ответа 1')),
                ('option2', models.CharField(max_length=255, verbose_name='Вариант ответа 2')),
                ('option3', models.CharField(max_length=255, verbose_name='Вариант ответа 3')),
                ('option4', models.CharField(max_length=255, verbose_name='Вариант ответа 4')),
                ('answer', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
