# Generated by Django 5.0.1 on 2024-01-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_question_marks_question_moduls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
