# Generated by Django 5.0.1 on 2024-01-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_remove_question_is_attempted_remove_question_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.CharField(blank=True, help_text='В формате часы:минуты:секунды<br/>Например: 00:30:00', max_length=8, null=True, verbose_name='Время на вопрос'),
        ),
    ]
