# Generated by Django 5.0.1 on 2024-01-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_remove_question_is_attempted_remove_question_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
    ]
