# Generated by Django 5.0.1 on 2024-01-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_alter_question_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
