# Generated by Django 5.0.1 on 2024-02-01 17:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_alter_question_is_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Вариант ответа 1'), ('Option2', 'Вариант ответа 2'), ('Option3', 'Вариант ответа 3'), ('Option4', 'Вариант ответа 4')], max_length=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_attempted',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='moduls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.moduls', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос'),
        ),
    ]
