# Generated by Django 5.0.1 on 2024-02-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_alter_question_answer_alter_question_is_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
