# Generated by Django 5.0.1 on 2024-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0031_alter_useranswer_question_alter_useranswer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=1, verbose_name='Варианты ответов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=8, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_attempted',
            field=models.BooleanField(default=True, verbose_name='Был отвечен'),
        ),
    ]
