# Generated by Django 5.0.1 on 2024-06-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0034_alter_useranswer_chosen_answer_delete_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Вариант ответа 1'), ('Option2', 'Вариант ответа 2'), ('Option3', 'Вариант ответа 3'), ('Option4', 'Вариант ответа 4')], max_length=8, verbose_name='Правильный вариатн ответа:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_attempted',
            field=models.BooleanField(blank=True, default=True, verbose_name='Пользователь может пересдать тест'),
        ),
    ]
