# Generated by Django 4.2.8 on 2024-01-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bg_image",
                    models.ImageField(
                        upload_to="ent/slider/", verbose_name="Задний фон"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Загаловок")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="ent/subjects/", verbose_name="Фото предмета"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Имя предмета"),
                ),
                (
                    "btn",
                    models.BooleanField(default=False, verbose_name="Основной предмет"),
                ),
            ],
        ),
    ]
