# Generated by Django 4.2.8 on 2024-01-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="image",
            field=models.ImageField(
                default=1, upload_to="ent/slider/", verbose_name="Картинка"
            ),
            preserve_default=False,
        ),
    ]
