# Generated by Django 5.0.1 on 2024-01-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0003_test_alter_slider_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
