# Generated by Django 5.0.1 on 2024-02-03 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0004_alter_slider_options_alter_subjects_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('option1', models.CharField(max_length=200, verbose_name='Вариант ответа 1')),
                ('option2', models.CharField(max_length=200, verbose_name='Вариант ответа 2')),
                ('option3', models.CharField(max_length=200, verbose_name='Вариант ответа 3')),
                ('option4', models.CharField(max_length=200, verbose_name='Вариант ответа 4')),
                ('answer', models.CharField(choices=[('Option1', 'Вариант ответа 1'), ('Option2', 'Вариант ответа 2'), ('Option3', 'Вариант ответа 3'), ('Option4', 'Вариант ответа 4')], max_length=8)),
                ('is_attempted', models.BooleanField(blank=True, default=True)),
                ('moduls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Вопросы', to='ent.subjects', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(max_length=255, verbose_name='Выбранный ответ')),
                ('is_correct', models.BooleanField(verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ent.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
