# Generated by Django 5.0.1 on 2024-02-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0006_remove_useranswer_question_remove_useranswer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionent',
            name='moduls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Вопросы_ENT', to='ent.subjects', verbose_name='Предмет ENT'),
        ),
    ]
