# Generated by Django 5.0.1 on 2024-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0007_alter_questionent_moduls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerent',
            name='chosen_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выбранный ответ'),
        ),
    ]
